version: "3.9"

services:
  frontend:
    build:
      context: ""
      dockerfile: Dockerfile
    image: "localhost:7002/ebb-${IMAGE_TYPE}-frontend_api:${IMAGE_TAG}"
    container_name: "${CONT_NAME}"
    ports:
      - "${PORT}:3000"
