version: "3.9"

services:
  frontend:
    build:
      context: ""
      dockerfile: Dockerfile.prod
    image: "localhost:7002/ebb-frontend-prod_api:${IMAGE_TAG}"
    container_name: "${CONT_NAME}"
    ports:
      - "80:80"
      - "443:443"
