FROM node:14.9.0 AS build-step

WORKDIR /build
COPY package.json package-lock.json ./
RUN npm install

COPY . .
RUN npm run build

FROM nginx:1.18-alpine
COPY nginx/conf/nginx.conf /etc/nginx/nginx.conf
COPY certbot/www /var/www/certbot
COPY --from=build-step /build/build /var/www/html