version: "3.9"

services:
  frontend:
    build:
      dockerfile: Dockerfile.prod
    container_name: "${CONT_NAME}"
    ports:
      - "${PORT}:80"
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www/:/var/www/certbot/:rw
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
